<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNMf8EbK\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNMf8EbK/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNMf8EbK.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNMf8EbK\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerNMf8EbK\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'NMf8EbK',
    'container.build_id' => '8392594e',
    'container.build_time' => 1549829725,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNMf8EbK');
